### ISSUE TITLE
Wpis utworzony: undefined

### ISSUE THREAD

**Issue by whinerpl** [marekfoltanski/seo-zabijaka#2]
Po stworzeniu artykułu przez opneai nie wrzuca go do wordpressa. Na dysku bez problemów 
Komunikat zwrotny:

1 / 171
index.js:64
piszę: Nazwa testowego artykułu?
openai.js:6
Zapisano tekst na dysku
functions.js:35
Wpis utworzony: undefined
index.js:40
-----------------------------------------

**Comment by sztossztos** [comment]
Sprobuj wrzucic bez kategorii i taga

**Comment by whinerpl** [comment]
dzięki, zadziałało

**Comment by marekfoltanski** [comment]
@whinerpl a tak z ciekawości, jak dodawałeś kategorie do csv? Muszą być podane jako ID, nie jako nazwa kategorii

**Comment by whinerpl** [comment]
tak, dalem tekst a nie id
